config/routes.rb
ContactManager::Application.routes.draw do
  root :to => "people#index"
  resources :companies

  resources :phone_numbers, :except => [:index, :show]
  resources :email_addresses, :except => [:index, :show]

  resources :people

  

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :people
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :phone_numbers, as: :contact
  has_many :email_addresses, as: :contact

  validates :name, presence: true
end

app/models/email_address.rb
class EmailAddress < ActiveRecord::Base
  belongs_to :contact, polymorphic: true

  validates :address, :contact_id, presence: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :phone_numbers, as: :contact
  has_many :email_addresses, as: :contact
  belongs_to :branch
  
  validates :first_name, :last_name, presence: true

  def self.by_last_name
    order("last_name")
  end
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :contact, polymorphic: true

  validates :number, :contact_id, :contact_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController

  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  def create
    @email_address = EmailAddress.new(email_params)
    if @email_address.save
      redirect_to @email_address.contact
      flash.notice = "This email was successfully added!"
    else
      render :new
    end
  end

  def destroy
    @email_address = EmailAddress.find(params[:id])
    @email_address.destroy
    redirect_to @email_address.contact
    flash.notice = "Email successfully deleted!"
  end

  def edit
    @email_address = EmailAddress.find(params[:id])
  end

  def update
    @email_address = EmailAddress.find(params[:id])
    @email_address.update(email_params)
    redirect_to @email_address.contact
    flash.notice = "Email successfully updated!"
  end

  private

  def email_params
    params.require(:email_address).permit(:address, :contact_id, :contact_type)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.by_last_name
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url 
    flash.notice = "#{@person.first_name} #{@person.last_name} successfully deleted!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  def index
    @phone_numbers = PhoneNumber.all
  end

  def show
  end

  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  def edit
  end

  def create
    @phone_number = PhoneNumber.new(phone_number_params)
   
    if @phone_number.save
      redirect_to @phone_number.contact, notice: 'Phone number was successfully created.'
    else
      render action: 'new'
    end
    
  end

  def update
    if @phone_number.update(phone_number_params)
      redirect_to @phone_number.contact, notice: 'Phone number was successfully updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @phone_number.destroy
    redirect_to @phone_number.contact
    flash.notice = "Phone number was successfully deleted!"
  end

  private
    
  def set_phone_number
    @phone_number = PhoneNumber.find(params[:id])
  end

  def phone_number_params
    params.require(:phone_number).permit(:number, :contact_id, :contact_type)
  end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Details', company %> |</td>
        <td><%= link_to 'Edit', edit_company_path(company) %> |</td>
        <td><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Phone Numbers:</strong>
  <% if @company.phone_numbers.empty? %>
  None
  <% end %>
</p>

<ul>
  <% @company.phone_numbers.each do |phone| %>
    <li><%= phone.number %> | 
        <%= link_to "Edit", edit_phone_number_path(phone) %> |
        <%= link_to "Delete", phone_number_path(phone), method: :delete, data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>

<p>
  <strong>Email Addresses:</strong>
  <% if @company.email_addresses.empty? %>
  None
  <% end %>
</p>

<ul>
  <% @company.email_addresses.each do |email| %>
    <li><%= email.address %> |
        <%= link_to "Edit", edit_email_address_path(email) %> |
        <%= link_to "Delete", email_address_path(email), method: :delete, data: { confirm: "Are you sure you want to delete this email?"} %></li>
  <% end %>
</ul>

<%= link_to 'Add Phone Number', new_phone_number_path(contact_id: @company.id, contact_type: 'Company') %> |
<%= link_to 'Add Email Address', new_email_address_path(contact_id: @company.id, contact_type: 'Company') %> |
<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/email_addresses/_form.html.erb
<%= form_for(@email_address) do |f| %>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_addresses/edit.html.erb
<h1>Edit email for <%= @email_address.person.first_name + " " + @email_address.person.last_name %></h1>

<%= render 'form' %>

app/views/email_addresses/new.html.erb
<% if @email_address.contact_type == "Person" %>
  <h1>Add a new email for <%= @email_address.contact.first_name + " " + @email_address.contact.last_name %></h1>
<% elsif @email_address.contact_type == "Company" %>
    <h1>Add a new email for <%= @email_address.contact.name %></h1>
<% end %>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactManager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<h3><%= link_to "All Contacts", people_path %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing <%= "#{@person.first_name} #{@person.last_name}'s Contact Info" %></h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>All Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= link_to 'Details', person %> |</td>
        <td><%= link_to 'Edit', edit_person_path(person) %> |</td>
        <td><%= link_to 'Delete', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Contact', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Phone Numbers:</strong>
  <% if @person.phone_numbers.empty? %>
  None
  <% end %>
</p>

<ul>
  <% @person.phone_numbers.each do |phone| %>
    <li><%= phone.number %> | 
        <%= link_to "Edit", edit_phone_number_path(phone) %> |
        <%= link_to "Delete", phone_number_path(phone), method: :delete, data: { confirm: "Are you sure you want to delete this number?" } %></li>
  <% end %>
</ul>

<p>
  <strong>Email Addresses:</strong>
  <% if @person.email_addresses.empty? %>
  None
  <% end %>
</p>

<ul>
  <% @person.email_addresses.each do |email| %>
    <li><%= email.address %> |
        <%= link_to "Edit", edit_email_address_path(email) %> |
        <%= link_to "Delete", email_address_path(email), method: :delete, data: { confirm: "Are you sure you want to delete this email?"} %></li>
  <% end %>
</ul>

<%= link_to 'Add Phone Number', new_phone_number_path(contact_id: @person.id, contact_type: 'Person') %> |
<%= link_to 'Add Email Address', new_email_address_path(contact_id: @person.id, contact_type: 'Person') %> |
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/phone_numbers/_form.html.erb
<%= form_for(@phone_number) do |f| %>
  <% if @phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @phone_number.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Edit This Phone Number</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_numbers_path %>